export let abnormalities = [
  {
    name: "derFreischutz",
    text: "text-slate-300",
    bg: "bg-[url('/assets/backgrounds/abnormalities/derFreischutz.png')]",
    // brightness: "backdrop-brightness-75",
    dullness: "bg-black/[0.25]",
    link: "https://www.goodreads.com/book/show/54270.Mein_Kampf",
    grad1: "from-blue-900/60",
    grad2: "to-black/60",
    pointersText: [
      "Freeshooter, dessen Kugeln immer ins Schwarze treffen.",
      "Möglicherweise rassistisch.",
    ],
    descText: ["Verschwunden zwischen 1933 und 1945. Für das Vaterland!"],
  },
  {
    name: "burrowingHeaven",
    text: "text-slate-300",
    bg: "bg-[url('/assets/backgrounds/abnormalities/burrowingHeaven.png')]",
    // brightness: "backdrop-brightness-50",
    dullness: "bg-black/50",
    link: "https://www.tumblr.com/blog/view/chickennuggetswrites/666079500835192832?source=share",
    grad1: "from-red-500/40",
    grad2: "to-red-400/40",
    pointersText: [
      "Really likes being looked at ( ͡º ͜ʖ ͡º)",
      "Wants to hog all your attention",
      "Will actively murder you if you look at others",
    ],
    descText: [
      "Basically an eldritch abomination that is also yandere (manga adaptation when?)",
    ],
  },
  {
    name: "blueStar",
    text: "text-slate-300",
    bg: "bg-[url('/assets/backgrounds/abnormalities/blueStar.png')]",
    // brightness: "backdrop-brightness-100",
    dullness: "bg-black/0",
    link: "https://www.wikifeet.com/",
    grad1: "from-blue-800/40",
    grad2: "to-blue-700/40",
    pointersText: [
      "Straight up immortal",
      "Has literally infinite worshippers",
      "Just as hard to fight one-handed",
    ],
    descText: [
      "Essentially just pandering to their core audience; anyone playing this game willingly is probably a foot fetishist too.",
    ],
  },
  {
    name: "whitenight",
    text: "text-red-700",
    bg: "bg-[url('/assets/backgrounds/abnormalities/whitenight.png')]",
    // brightness: "backdrop-brightness-75",
    dullness: "bg-black/[0.25]",
    link: "https://www.heavensgate.com/",
    grad1: "from-gray-500/40",
    grad2: "to-gray-400/40",
    pointersText: [
      "Literally, unironically, God",
      "He/Him (mind the capitalization, He gets sensitive about this)",
      "Epic 90 minute battle",
    ],
    descText: [
      "Ravages and insta-kills most of your fighters only to be backstabbed and die to an imposter; possibly a reference to hit indie multiplayer mobile game Among Us",
    ],
  },
  {
    name: "punishingBird",
    text: "text-slate-300",
    bg: "bg-[url('/assets/backgrounds/abnormalities/punishingBird.png')]",
    // brightness: "backdrop-brightness-50",
    dullness: "bg-black/50",
    link: "https://imgur.com/a/H60kM8n",
    grad1: "from-yellow-700/90",
    grad2: "to-black/60",
    pointersText: ["is smol", "is borb"],
    descText: [
      "smol borb.",
      "btw the abnormalities on this page are arranged in ascending order of how much damage they can deal",
    ],
  },
];
