export const songDetails = [
  {
    name: "lovetown",
    bg: "bg-pink-400",
    border: "border-pink-400",
    link: "https://youtu.be/xyx8DMlUAQ4",
    title: "Lovetown",
    titleStyle: "text-pink-600",
    playerStyle: "bg-pink-300",
    song: "From a Place of Love",
    genre: "PTSD",
    desc: `A beautiful and innocent song for the story of a couple, the genre of which devolves quickly from "Love" to "Lovecraftian" in the span of one visual novel cutscene. I still get nightmares about this storyline! :D`,
    fact: `For a long while, the game wiki page for this battle was just the text "we don't talk about Lovetown".`,
  },
  {
    name: "cryingchildren",
    bg: "bg-gray-400",
    border: "border-gray-400",
    link: "https://youtu.be/lclt459JpVQ",
    title: "The Crying Children",
    titleStyle: "text-gray-300",
    playerStyle: "bg-gray-300",
    song: "And Then is Heard No More",
    genre: "Cope",
    desc: `The Song of a maidenless soyboy who somehow runs away and survives like the first four times he battles you, and wishes he'd died each time afterwards.`,
    fact: `This fight was the reason I had "kill more crying children" written in my notes.`,
  },
  {
    name: "xiao",
    bg: "bg-red-700",
    border: "border-red-700",
    link: "https://youtu.be/UeBQMVnmr2Y",
    title: "Xiao",
    titleStyle: "text-red-500",
    playerStyle: "bg-red-600",
    song: "Iron Lotus",
    genre: "FIRE",
    desc: `Theme for a w*man who just wants to avenge her dead husband. If being cute was a crime, Xiao would be in jail; for twelve charges of manslaughter via arson`,
    fact: `Despite the song's theming about rage and fire this is the only boss that is fully sane and in control of her emotions during the fight.`,
  },
  {
    name: "yan",
    bg: "bg-blue-500",
    border: "border-blue-500",
    link: "https://youtu.be/aHUVqV5CO6w",
    title: "Distorted Yan",
    titleStyle: "text-blue-300",
    playerStyle: "bg-blue-400",
    song: "Children of the City",
    genre: "JEE",
    desc: `Based man concludes free will doesn't exist, breaks into local library for shits and giggles because a piece of paper told him to. Truly a masterpiece of storytelling.`,
    fact: `The line in the song "By the time you realise, you'll be restrained to a desk / And with your dreams on the floor your comply, eyes chained to the test" really resonates with me for some reason, not quite sure why though.`,
  },
  {
    name: "blacksilence",
    bg: "bg-black",
    border: "border-black",
    link: "https://youtu.be/D_qiWvjJ3kk",
    title: "The Black Silence",
    titleStyle: "text-white",
    playerStyle: "bg-black",
    song: "Gone Angels",
    genre: "Depression",
    desc: `/assets/trolldespair.png`,
    descIsImage: true,
    fact: `There's a lore reason for why the only instrument in the song is a piano.`,
  },
];
