import Head from "next/head";
import { Topbar } from "../components/topbar";
import { Title } from "../components/homepage/title";
import { Contents } from "../components/homepage/contents";
import { useEffect } from "react";

export default function Home() {
  useEffect(() => {
    document.body.classList.add("bg-[url(/assets/homepage.png)]");
    document.body.classList.add("bg-fixed");
    document.body.classList.add("bg-top");
    document.body.classList.add("bg-cover");
  });
  return (
    <>
      <Head>
        <title>Welcome back to Hell</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Topbar />
      <Title />

      <div className="bg-gray-800 w-screen mt-96">
        <div className="z-0 text-slate-300 text-xl max-w-6xl mx-auto py-8 lg:py-8">
          <Contents />
        </div>
      </div>
    </>
  );
}
