import Head from "next/head";
import { Topbar } from "../components/topbar";
import { HomeTitle } from "../components/homepage/homeTitle";
import { HomeContent } from "../components/homepage/homeContent";
import { ContentContainer } from "../components/common/contentContainer";
import { PageContainer } from "../components/common/pageContainer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome back to Hell</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <PageContainer innerBackground="bg-[url('/assets/homepage.png')]">
        <HomeContents />
      </PageContainer>
    </>
  );
}

function HomeContents() {
  return (
    <>
      <Topbar />
      <HomeTitle />
      <div className="bg-gray-800 w-full mt-96">
        <ContentContainer>
          <HomeContent />
        </ContentContainer>
      </div>
    </>
  );
}
