import Head from "next/head";
import { Topbar } from "../components/topbar";
import { HomeTitle } from "../components/homepage/homeTitle";
import { HomeContents } from "../components/homepage/homeContents";
import { ContentContainer } from "../components/common/contentContainer";
import { PageContainer } from "../components/common/pageContainer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome back to Hell</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <PageContainer
        innerBackground="bg-[url('/assets/homepage.png')]"
        handlers={{}}
      >
        <Topbar />
        <HomeTitle />
        <div className="bg-gray-800 w-screen mt-96">
          <ContentContainer>
            <HomeContents />
          </ContentContainer>
        </div>
      </PageContainer>
    </>
  );
}
